//
//  TempModelsTBServer.swift
//  CCMarketPlace
//
//  Created by Gwendolyn Hardwick on 3/28/24.
//

import Foundation

// temporary models for testing the views with. Kept for posterities sake
var tempProductsList = [
    Product(id: UUID(),
            title: "thing",
            description: "Spaghetti is a long, thin, solid, cylindrical pasta.[1] It is a staple food of traditional Italian cuisine. Like other pasta, spaghetti is made of milled wheat, water, and sometimes enriched with vitamins and minerals. Italian spaghetti is typically made from durum-wheat semolina.[2] Usually the pasta is white because refined flour is used, but whole wheat flour may be added. Spaghettoni is a thicker form of spaghetti, while spaghettini is a thinner form.",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_1", "Image_2"],
            buyPrice: 1.00),
    Product(id: UUID(),
            title: "Ceramic Vase",
            description: "As with dogs from other working breeds, the Australian Cattle Dog is energetic and intelligent with an independent streak. It responds well to structured training, particularly if it is interesting and challenging. It was originally bred to herd by biting, and is known to nip running children.",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_2"],
            buyPrice: 2.10),
    Product(id: UUID(),
            title: "Waterbottle",
            description: "Australian Cattle Dog has been nicknamed a Red Heeler or Blue Heeler on the basis of its colouring and practice of moving reluctant cattle by nipping at their heels. The nickname Queensland Heeler may have originated in a popular",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_3"],
            buyPrice: 3.15),
    Product(id: UUID(),
            title: "Waterbottle",
            description: "The cat (Felis catus), commonly referred to as the domestic cat or house cat, is the only domesticated species in the family Felidae. Recent advances in archaeology and genetics have shown that the domestication of the cat occurred in the Near East around 7500 BC. It is commonly kept as a house pet and farm cat, but also ranges freely as a feral cat avoiding human contact.",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_4"],
            buyPrice: 4.00),
    Product(id: UUID(),
            title: "Nightstand",
            description: "The origin of the English word cat, Old English catt, is thought to be the Late Latin word cattus, which was first used at the beginning of the 6th century.[4] The Late Latin word may be derived from an unidentified African language",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_5"],
            buyPrice: 5.00),
    Product(id: UUID(),
            title: "Bike Helmet",
            description: "The domestic cat is a member of the Felidae, a family that had a common ancestor about 10 to 15 million years ago.",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_6"],
            buyPrice: 6.10),
    Product(id: UUID(),
            title: "thing",
            description: "It was long thought that the domestication of the cat began in ancient Egypt, where cats were venerated from around 3100 BC,[31][32] However, the earliest known indication for the taming of an African wildcat was excavated close by a human Neolithic grave in Shillourokambos, southern Cyprus, dating to about 7500–7200 BC.",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_7"],
            buyPrice: 7.10),
    Product(id: UUID(),
            title: "Suitcase",
            description: "Development of cat breeds started in the mid 19th century",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_8"],
            buyPrice: 8.10),
    Product(id: UUID(),
            title: "TV",
            description: "Cats have excellent night vision and can see at one sixth the light level required for human vision.[51]: 43  This is partly the result of cat eyes having a tapetum lucidum, which reflects any light that passes through the retina back into the eye, thereby increasing the eye's sensitivity to dim light",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_9"],
            buyPrice: 9.10),
    Product(id: UUID(),
            title: "thing",
            description: "The domestic cat's hearing is most acute in the range of 500 Hz to 32 kHz",
            dateListed: "3/28/2024",
            tags: [],
            imageIds: ["Image_10"],
            buyPrice: 10.10)
        ]

var tempStudentList = [
    Student(id: UUID(),
            name: "Jane Doe",
            email: "J_Doe@ColoradoCollege.edu",
            classYear: "Senior",
            imageId: "Image_3",
            userRating: 2.5,
            reviews: [],
            productSet: [tempProductsList[0]],
            purchases: [],
            likedSet: []),
    Student(id: UUID(),
            name: "John Doe",
            email: "J_Doe@ColoradoCollege.edu",
            classYear: "Senior",
            userRating: 1.5,
            reviews: [],
            productSet: [],
            purchases: [],
            likedSet: []),
    Student(id: UUID(),
            name: "Ronald McDonald",
            email: "R_McDonald@ColoradoCollege.edu",
            classYear: "Junior",
            userRating: 0.2,
            reviews: [],
            productSet: [],
            purchases: [],
            likedSet: []),
    Student(id: UUID(),
            name: "Mary HadaLamb",
            email: "M_HadaLamb@ColoradoCollege.edu",
            classYear: "Freshman",
            userRating: 2.8,
            reviews: [],
            productSet: [],
            purchases: [],
            likedSet: [])
]
